--AGREGARLES LOS FK A LAS TABALAS PARA QUE FUNCIONE EL ALTER TABLE


-- Database: PaginaWebGaming

-- DROP DATABASE "PaginaWebGaming";

--CREATE DATABASE "PaginaWebGaming"
--    WITH 
  --  OWNER = postgres
    --ENCODING = 'UTF8'
    --LC_COLLATE = 'Spanish_Spain.1252'
    --LC_CTYPE = 'Spanish_Spain.1252'
    --TABLESPACE = pg_default
    --CONNECTION LIMIT = -1;

--COMMENT ON DATABASE "PaginaWebGaming"
  --  IS 'Base de datos para mi pagina web Gamer version 1';
	CREATE TABLE USUARIOS(
	PK_USUARIOID int NOT NULL,
	NOMBREAPELLIDO varchar(50) NOT NULL,
	USERNAME varchar(30) NOT NULL,
	FECHA_NAC date NOT NULL,
	PASS varchar(30) NOT NULL,
	EMAIL varchar(30) NOT NULL,
	ESTADO bool NOT NULL,
	FK_GENERO int NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY (PK_USUARIOID));
	
CREATE TABLE GENEROS(
PK_GENEROID int NOT NULL,
NOMBRE varchar(30) NOT NULL,
CONSTRAINT PK_GENERO PRIMARY KEY (PK_GENEROID));

CREATE TABLE ESPECIALIZACIONES(
PK_ESPECIALIDADID int NOT NULL,
NOMBRE varchar(30) NOT NULL,
DESCRIPCION varchar(50) NULL,
CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (PK_ESPECIALIDADID));

CREATE TABLE MENSAJES(
PK_MENSAJEID int NOT NULL,
TEXTOMSG text NULL,
FECHAMSG date NOT NULL,
CONSTRAINT PK_MENSAJE PRIMARY KEY (PK_MENSAJEID));
									 
CREATE TABLE SEGUIDORES (
PK_SEGUIDORID int NOT NULL,
NOMBREAPELLIDO varchar(50) NULL,
EMAIL varchar(30) NOT NULL,
CONSTRAINT PK_SEGUIDOR PRIMARY KEY (PK_SEGUIDORID));
									
CREATE TABLE FOTOSPERFILES(
DESCRIPCION varchar(100) NULL
);

CREATE TABLE USUARIOSXPROYECTOS(
FK_USUARIOSID int NOT NULL,
FK_PROYECTOID int NOT NULL,

);

									 
CREATE TABLE FOTOS(
PK_FOTOID int NOT NULL,
TITULOFOTO varchar(30) NOT NULL,
ARCHIVO MEDIUMBLOB NOT NULL,
DESCRIPCION varchar(100) NULL,
CONSTRAINT PK_FOTO PRIMARY KEY (PK_FOTOID));
							
CREATE TABLE PUNTOSEXP(
PK_PUNTOID int NOT NULL,
PUNTAJETOTAL numeric NOT NULL,
CONSTRAINT PK_PUNTO PRIMARY KEY (PK_PUNTOID));
								
CREATE TABLE NIVELES(
PK_NIVELID int NOT NULL,
NOMBRENIVEL varchar(30) NOT NULL,
DESCRIPCIONNIVEL varchar(100) NULL,
DESCRIPCION varchar(100) NULL,
CONSTRAINT PK_NIVEL PRIMARY KEY (PK_NIVELID));
								
CREATE TABLE FEEDBACKS(
PK_FEEDBACKID int NOT NULL,
COMENTARIO varchar(150) NOT NULL,
CONSTRAINT PK_FEEDBACK PRIMARY KEY (PK_FEEDBACKID));
								
CREATE TABLE FOROS(
PK_FOROID int NOT NULL,
DESCRIPCION varchar(100) NULL,
ESTADO bool NOT NULL,
FECHACREACION date NOT NULL,
CONSTRAINT PK_FORO PRIMARY KEY (PK_FOROID));
								
CREATE TABLE RESPUESTAS(
TEXTO text NOT NULL);
								
CREATE TABLE TIPOSFORO(
PK_TIPOFOROID int NOT NULL,
NOMBRE varchar(30) NOT NULL,
DESCRIPCION varchar(100) NULL,
CONSTRAINT PK_TIPOFORO PRIMARY KEY (PK_TIPOFOROID));
								
CREATE TABLE PROYECTOS(
PK_PROYECTOID int NOT NULL,
DESCRIPCION varchar(100) NOT NULL,
ESTADO bool NOT NULL,
FECHACREACION date NOT NULL,
FECHAFINALIZACION date NULL,
CONSTRAINT PK_PROYECTO PRIMARY KEY (PK_PROYECTOID));
								
CREATE TABLE ARTICULOS(
PK_ARTICULOID int NOT NULL,
FECHACREACION date NOT NULL,
DESCRIPCION varchar(100) NULL,
ESTADO bool NOT NULL,
CONSTRAINT PK_ARTICULO PRIMARY KEY (PK_ARTICULOID));
								
CREATE TABLE TIPOARTICULOS(
PK_TIPOARTICULOID int NOT NULL,
NOMBRE varchar(30) NOT NULL,
DESCRIPCION varchar(100) NULL,
CONSTRAINT PK_TIPOARTICULO PRIMARY KEY (PK_TIPOARTICULOID));
								
CREATE TABLE VIDEOS(
PK_VIDEOID int NOT NULL,
TITULOVIDEO varchar(30) NOT NULL,
ARCHIVO MEDIUMBLOB NOT NULL,
DESCRIPCION varchar(100) NULL,
CONSTRAINT PK_VIDEO PRIMARY KEY (PK_VIDEOID));


ALTER TABLE USUARIOSXPROYECTOS
ADD CONSTRAINT FK_USUARIOS FOREIGN KEY(FK_USUARIOSID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;

ALTER TABLE USUARIOSXPROYECTOS
ADD CONSTRAINT FK_PROYECTO FOREIGN KEY(FK_PROYECTOID)
REFERENCES PROYECTOS (PK_PROYECTOID)
on delete restrict on update restrict;
								
ALTER TABLE USUARIOS
ADD CONSTRAINT FK_GENERO FOREIGN KEY(FK_GENEROID)
REFERENCES GENEROS (PK_GENEROID)
on delete restrict on update restrict;
		
ALTER TABLE SEGUIDORES
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								
ALTER TABLE MENSAJES
ADD CONSTRAINT FK_SEGUIDOR FOREIGN KEY(FK_SEGUIDORID)
REFERENCES SEGUIDORES (PK_SEGUIDORID)
on delete restrict on update restrict;
								 
ALTER TABLE MENSAJES
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE PROYECTOS
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE FOTOSPERFILES
ADD CONSTRAINT FK_FOTO FOREIGN KEY(FK_FOTOID)
REFERENCES FOTOS (PK_FOTOID)
on delete restrict on update restrict;
						
ALTER TABLE FOTOSPERFILES
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE USUARIOSXPROYECTOS
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
							
ALTER TABLE USUARIOSXPROYECTOS
ADD CONSTRAINT FK_PROYECTO FOREIGN KEY(FK_PROYECTOID)
REFERENCES PROYECTOS (PK_PROYECTOID)
on delete restrict on update restrict;
								 
ALTER TABLE FOROS
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE RESPUESTAS
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE RESPUESTAS
ADD CONSTRAINT FK_FORO FOREIGN KEY(FK_FOROID)
REFERENCES FOROS (PK_FOROID)
on delete restrict on update restrict;
								 
ALTER TABLE FOTOS
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE PUNTOSEXP
ADD CONSTRAINT FK_PUNTO FOREIGN KEY(FK_PUNTOID)
REFERENCES PUNTOSEXP (PK_PUNTOID)
on delete restrict on update restrict;
								 
ALTER TABLE FEEDBACKS
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE ESPECIALIZACIONES
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_TIPOARTICULO FOREIGN KEY(FK_TIPOARTICULOID)
REFERENCES TIPOARTICULOS (PK_TIPOARTICULOID)
on delete restrict on update restrict;
								 
ALTER TABLE VIDEOS
ADD CONSTRAINT FK_USUARIOS FOREIGN KEY(FK_USUARIOID)
REFERENCES USUARIOS (PK_USUARIOID)
on delete restrict on update restrict;
								 
ALTER TABLE VIDEOS
ADD CONSTRAINT FK_ARTICULO FOREIGN KEY(FK_ARTICULOID)
REFERENCES ARTICULOS (PK_ARTICULOID)
on delete restrict on update restrict;